### ISSUE TITLE
Invalid directory argument

### ISSUE THREAD

**Issue by ahmedsadman** [IshrakAbedin/DockerRocker#1]
When running in Windows environment, it shows an error similar to:
`OSError: [Errno 22] Invalid argument: 'F:\\_Dev\\DockerRocker/F:\\_Dev\\DockerRocker\\rocker.json'`

It's because the directory parsing is not done correctly, and the current solution is not universal.

**Comment by ahmedsadman** [comment]
Fix addressed in #2

**Comment by IshrakAbedin** [comment]
Fixed and works for Windows and Linux
