### ISSUE TITLE
Problems with .gitignore (pycache issue)

### ISSUE THREAD

**Issue by ahmedsadman** [IshrakAbedin/DockerRocker#4]
- Find a way to ignore `__pycache__` folder and `.*pyc` folders/files altogether. Making `.gitignore` work properly is a fix

- Add `Dockerfile` and `rocker.json` (including files that are generated on the go) to `.gitignore`, as they are not part of the original code and is meant to be generated by the user

**Comment by IshrakAbedin** [comment]
Fixed
